spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_FETCH_REGISTRY}
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
