spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-srv
              uri: lb://auth-srv
              predicates:
                - Path=/auth/**
            - id: event-srv
              uri: lb://event-srv
              predicates:
                - Path=/event,/event/**,/event-venue,/event-venue/**

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
