spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-srv
              uri: lb://auth-srv
              predicates:
                - Path=/auth/**
            - id: event-srv
              uri: lb://event-srv
              predicates:
                - Path=/event,/event/**,/event-venue,/event-venue/**

server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
