spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED}
      path: ${H2_CONSOLE_PATH}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}

server:
  port: ${SERVER_PORT}

user-srv:
  base-url: ${USER_SRV_BASE_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration-seconds: ${JWT_EXPIRATION_SECONDS}
